const searchIndex = [
  // Core GX
  { name: "Rendering", link: "GXDocs/Rendering.html", keywords: "gpu, framebuffer, display, video, GX_Init, VIDEO_Configure, VIDEO_SetNextFramebuffer, initialization, efb, xfb" },
  { name: "Primitives", link: "GXDocs/Primitives.html", keywords: "triangles, quads, lines, shapes, GX_Begin, GX_End, GX_TRIANGLES, GX_QUADS, vertices, geometry" },
  { name: "Textures", link: "GXDocs/Textures.html", keywords: "TPL, GX_InitTexObj, GX_LoadTexObj, filtering, wrapping, mipmaps, texture mapping, UV coordinates" },
  { name: "Matrices", link: "GXDocs/Matrices.html", keywords: "modelview, projection, guMtxIdentity, guMtxTrans, guPerspective, transformation, rotation, scaling" },
  { name: "Lighting", link: "GXDocs/Lighting.html", keywords: "ambient, diffuse, specular, GX_SetChanCtrl, GX_SetLightPos, GX_SetNumChans, materials, shading" },
  { name: "State Management", link: "GXDocs/StateManagement.html", keywords: "blending, depth test, culling, z-buffer, GX_SetBlendMode, GX_SetZMode, render states" },

  // Guides & Tools
  { name: "Tutorials", link: "GXDocs/Tutorials.html", keywords: "advanced, optimization, best practices, examples, 3D scene, texture mapping, performance, debugging" },
  { name: "Basic 3D Scene", link: "GXDocs/Tutorials.html#basic-3d-scene", keywords: "3D, cube, rotation, projection matrix, depth testing, tutorial" },
  { name: "Texture Tutorial", link: "GXDocs/Tutorials.html#texture-tutorial", keywords: "texture mapping, UV coordinates, TPL, gxtexconv, quad" },
  { name: "Performance Optimization", link: "GXDocs/Tutorials.html#performance-optimization", keywords: "display lists, memory alignment, DMA, optimization, batching" },
  { name: "Debugging Tips", link: "GXDocs/Tutorials.html#debugging-tips", keywords: "debugging, troubleshooting, common pitfalls, frame timing, matrix stack" },
  { name: "Useful Structs", link: "GXDocs/UsefulStructs.html", keywords: "data structures, guVector, Mtx, GXColor, GXRModeObj, GXTexObj, WPADData" },
  { name: "GXRModeObj", link: "GXDocs/UsefulStructs.html#GXRModeObj", keywords: "video mode, screen dimensions, framebuffer format, fbWidth, efbHeight" },
  { name: "guVector", link: "GXDocs/UsefulStructs.html#guVector", keywords: "3D vector, position, normal, direction, x y z coordinates" },
  { name: "Mtx Matrix", link: "GXDocs/UsefulStructs.html#Mtx", keywords: "4x3 matrix, transformation, modelview, projection, GX_LoadPosMtxImm" },
  { name: "GXColor", link: "GXDocs/UsefulStructs.html#GXColor", keywords: "color, RGBA, red green blue alpha, 8-bit components" },
  { name: "GXTexObj", link: "GXDocs/UsefulStructs.html#GXTexObj", keywords: "texture object, texture information, dimensions, format, filtering" },
  { name: "WPADData", link: "GXDocs/UsefulStructs.html#WPADData", keywords: "wiimote input, button states, accelerometer, IR pointer, extensions" },
  { name: "Miscellaneous", link: "GXDocs/Misc.html", keywords: "best practices, types, variables, debugging, logger, variable naming" },

  // Accessories
  { name: "Miis", link: "GXDocs/Miis.html", keywords: "Mii, character, avatar, mii_init, mii_get_all_miis, libwiimisc, NAND database" },
  { name: "Wiimote Core", link: "GXDocs/WiimoteCore.html", keywords: "wpad, input, buttons, accelerometer, rumble, leds, power, battery, WPAD_Init, WPAD_ScanPads" },
  { name: "WPAD_Init", link: "GXDocs/WiimoteCore.html#initialization", keywords: "wiimote initialization, WPAD_Init, WPAD_ScanPads, setup" },
  { name: "WPAD_ScanPads", link: "GXDocs/WiimoteCore.html#reading-input", keywords: "scan input, read buttons, WPAD_ButtonsDown, WPAD_ButtonsHeld" },
  { name: "WPAD_SetRumble", link: "GXDocs/WiimoteCore.html#rumble", keywords: "rumble, vibration, WPAD_SetRumble, haptic feedback" },
  { name: "WPAD_SetLEDs", link: "GXDocs/WiimoteCore.html#leds", keywords: "LEDs, lights, WPAD_SetLEDs, player indicators" },
  { name: "SYS_SetPowerCallback", link: "GXDocs/WiimoteCore.html#power-management", keywords: "power button, shutdown, SYS_SetPowerCallback, home button" },
  { name: "IR Pointer", link: "GXDocs/IR.html", keywords: "infrared, cursor, aiming, sensor bar, WPAD_SetVRes, ir_t, pointer coordinates" },
  { name: "WPAD_SetDataFormat", link: "GXDocs/IR.html#initialization", keywords: "data format, IR data, WPAD_FMT_BTNS_ACC_IR" },
  { name: "WPAD_SetVRes", link: "GXDocs/IR.html#initialization", keywords: "virtual resolution, screen mapping, IR pointer scaling" },
  { name: "ir_t struct", link: "GXDocs/IR.html#reading-data", keywords: "IR data structure, pointer coordinates, valid, angle, raw coordinates" },
  { name: "Nunchuk", link: "GXDocs/Nunchuk.html", keywords: "expansion, analog stick, joystick, C button, Z button, WPAD_EXP_NUNCHUK, acceleration" },
  { name: "WPAD_EXP_NUNCHUK", link: "GXDocs/Nunchuk.html#enabling", keywords: "nunchuk detection, expansion type, WPAD_EXP_NUNCHUK" },
  { name: "joystick_t", link: "GXDocs/Nunchuk.html#reading-data", keywords: "analog stick, joystick data, x y coordinates, magnitude, angle" },
  { name: "NUNCHUK_BUTTON_C", link: "GXDocs/Nunchuk.html#buttons", keywords: "C button, nunchuk buttons, NUNCHUK_BUTTON_C, NUNCHUK_BUTTON_Z" },
  { name: "MotionPlus", link: "GXDocs/MotionPlus.html", keywords: "gyroscope, gyro, 1:1 motion, WPAD_EXP_MOTIONPLUS, WPAD_ActivateMotionPlus, angular velocity" },
  { name: "WPAD_ActivateMotionPlus", link: "GXDocs/MotionPlus.html#activation", keywords: "motion plus activation, gyroscope enable, WPAD_ActivateMotionPlus" },
  { name: "gyro_t", link: "GXDocs/MotionPlus.html#reading-data", keywords: "gyroscope data, angular velocity, pitch yaw roll, rotation rate" },
  { name: "Classic Controller", link: "GXDocs/ClassicController.html", keywords: "gamepad, pro, virtual console, WPAD_EXP_CLASSIC, CLASSIC_BUTTON_A, analog sticks, triggers" },
  { name: "CLASSIC_BUTTON_A", link: "GXDocs/ClassicController.html#button-constants", keywords: "classic controller buttons, A B X Y buttons, CLASSIC_BUTTON_A" },
  { name: "classic controller triggers", link: "GXDocs/ClassicController.html#reading-data", keywords: "analog triggers, ltrig rtrig, shoulder buttons, L R ZL ZR" },
  { name: "Balance Board", link: "GXDocs/BalanceBoard.html", keywords: "wii fit, weight, pressure sensor, center of gravity, WPAD_EXP_BALANCE, calibration" },
  { name: "balance_t", link: "GXDocs/BalanceBoard.html#reading-data", keywords: "balance board data, weight sensors, tl tr bl br, center of gravity" },
  { name: "balance board calibration", link: "GXDocs/BalanceBoard.html#calibration", keywords: "calibration, zeroing, offset compensation, accurate readings" },

  // Function References
  { name: "GX_Init", link: "GXDocs/Rendering.html", keywords: "GX initialization, graphics initialization, FIFO setup" },
  { name: "VIDEO_Configure", link: "GXDocs/Rendering.html", keywords: "video configuration, display setup, video mode" },
  { name: "GX_SetViewport", link: "GXDocs/Rendering.html", keywords: "viewport, screen area, rendering region" },
  { name: "GX_LoadProjectionMtx", link: "GXDocs/Matrices.html", keywords: "projection matrix, perspective, orthographic" },
  { name: "GX_LoadPosMtxImm", link: "GXDocs/Matrices.html", keywords: "modelview matrix, position matrix, transformation" },
  { name: "GX_SetNumChans", link: "GXDocs/Lighting.html", keywords: "lighting channels, color channels, material colors" },
  { name: "GX_SetBlendMode", link: "GXDocs/StateManagement.html", keywords: "blending, alpha blending, transparency" },
  { name: "GX_SetZMode", link: "GXDocs/StateManagement.html", keywords: "depth testing, z-buffer, depth comparison" },
  { name: "GX_Begin", link: "GXDocs/Primitives.html", keywords: "begin primitive, start geometry, vertex submission" },
  { name: "GX_End", link: "GXDocs/Primitives.html", keywords: "end primitive, finish geometry, complete drawing" },
  { name: "GX_Position3f32", link: "GXDocs/Primitives.html", keywords: "vertex position, 3D coordinates, geometry data" },
  { name: "GX_Normal3f32", link: "GXDocs/Primitives.html", keywords: "vertex normal, lighting calculation, surface direction" },
  { name: "GX_TexCoord2f32", link: "GXDocs/Primitives.html", keywords: "texture coordinates, UV mapping, texture position" },
  { name: "TPL_OpenTPLFromMemory", link: "GXDocs/Textures.html", keywords: "TPL file loading, texture loading, TPL format" },
  { name: "GX_InitTexObj", link: "GXDocs/Textures.html", keywords: "texture object initialization, texture setup" },
  { name: "GX_LoadTexObj", link: "GXDocs/Textures.html", keywords: "load texture, bind texture, texture activation" }
];
